# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.4.1
FROM docker.io/library/ruby:$RUBY_VERSION-slim

# Install dependencies
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y build-essential curl git libpq-dev postgresql-client && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Set working directory
WORKDIR /rails

# Run and own only the runtime files as a non-root user for security
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN groupadd --force --system --gid $GROUP_ID rails && \
  useradd rails --uid $USER_ID --gid $GROUP_ID --create-home --shell /bin/bash

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install && \
  rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
  bundle exec bootsnap precompile --gemfile

# Copy entrypoint script
COPY bin/docker-entrypoint-dev /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint-dev
ENTRYPOINT ["docker-entrypoint-dev"]

USER $USER_ID:$GROUP_ID

# Configure the main process to run when running the image
EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-P", "/tmp/server.pid"]
